title = "blank's blog"
baseurl = "https://blank-lee.github.io"
languageCode = "zh-tw"
theme = "PaperMod"
buildDrafts = false

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 10

[[menu.main]]
identifier = "categories"
name = "categories"
url = "/categories/"
weight = 20

[[menu.main]]
identifier = "archives"
name = "Archives"
url = "/archives/"
weight = 30


[params.profileMode]
enabled = true
title = "blank"
subtitle = ":P"
imageUrl = "img/name.png"
imageWidth = 120
imageHeight = 120
imageTitle = "..."

[[params.profileMode.buttons]]
name = "Blog"
url = "/posts/"

[[params.profileMode.buttons]]
name = "Categories"
url = "/categories/"

[[params.socialicons]]
name = "github"
url = "https://github.com/blank-lee"

[[params.socialicons]]
name = "email"
url = "mailto:blank060706@gmail.com"


[params]
ShowBreadCrumbs = true
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true

[params.cover]
linkFullImage = true
